export interface ProductItem {
  id: string;
  name: string;
  hindiName: string;
  marathiName: string;
  category: 'Vegetables' | 'Grains' | 'Fruits' | 'Spices' | 'Pulses';
  pricePerKg: number;
  mrp: number;
  discountPercent: number;
  rating: number;
  reviewCount: number;
  isBestSeller?: boolean;
  isFreshCertified?: boolean;
  availableQuantity: number;
  minOrderQuantity: number;
  unit: string;
  grade: 'Grade A+' | 'Grade A' | 'Grade B';
  farmLocation: string;
  district: string;
  state: string;
  farmerName: string;
  farmerPhone: string;
  kisanId: string; // Govt certified Kisan ID
  barcode: string; // Unique anti-fraud barcode
  harvestDate: string;
  organic: boolean;
  labCertificateNo?: string;
  labName?: string;
  labTestDate?: string;
  labResidueResult?: string;
  image: string;
  description: string;
  shelfLifeDays: number;
  boughtPastMonth: string;
}

export const INITIAL_PRODUCTS: ProductItem[] = [
  {
    id: 'prod-001',
    name: 'Fresh Hybrid Tomatoes (Tamatar)',
    hindiName: 'ताज़ा हाइब्रिड टमाटर',
    marathiName: 'ताजे हायब्रिड टोमॅटो',
    category: 'Vegetables',
    pricePerKg: 28,
    mrp: 40,
    discountPercent: 30,
    rating: 4.6,
    reviewCount: 3420,
    isBestSeller: true,
    isFreshCertified: true,
    availableQuantity: 2400,
    minOrderQuantity: 1,
    unit: 'kg',
    grade: 'Grade A+',
    farmLocation: 'Pimpalgaon Baswant',
    district: 'Nashik',
    state: 'Maharashtra',
    farmerName: 'Patil Organic Farms',
    farmerPhone: '+91 98221 44521',
    kisanId: 'MH-KISAN-902148',
    barcode: 'CRPNX-AGRI-MH01-94218',
    harvestDate: 'Fresh harvested today morning',
    organic: true,
    labCertificateNo: 'NPOP/NABL/AGRI-2026-4491',
    labName: 'FSSAI Accredited Maharashtra Agri Quality Lab, Pune',
    labTestDate: '28 Sep 2026',
    labResidueResult: '0.00% Pesticide Residue Detected (100% Organic PASS)',
    image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=600&q=80',
    description: 'Farm-fresh, naturally ripened plump hybrid tomatoes directly sourced from Nashik orchards. High in lycopene with firm skin and rich flavor.',
    shelfLifeDays: 8,
    boughtPastMonth: '2K+ orders this month',
  },
  {
    id: 'prod-002',
    name: 'Nashik Red Onion (Pyaaz / Kanda)',
    hindiName: 'नासिक लाल प्याज',
    marathiName: 'नाशिक लाल कांदा (गरवा)',
    category: 'Vegetables',
    pricePerKg: 34,
    mrp: 50,
    discountPercent: 32,
    rating: 4.7,
    reviewCount: 5120,
    isBestSeller: true,
    isFreshCertified: true,
    availableQuantity: 8500,
    minOrderQuantity: 2,
    unit: 'kg',
    grade: 'Grade A',
    farmLocation: 'Lasalgaon Mandi Belt',
    district: 'Nashik',
    state: 'Maharashtra',
    farmerName: 'Shinde Agro Ventures',
    farmerPhone: '+91 94230 89123',
    kisanId: 'MH-KISAN-812044',
    barcode: 'CRPNX-AGRI-MH02-88124',
    harvestDate: 'Cured & ventilated batch',
    organic: false,
    image: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&w=600&q=80',
    description: 'Authentic Lasalgaon Garwa red onions. Crisp, pungent with dry paper skins ensuring long shelf storage without sprouting.',
    shelfLifeDays: 45,
    boughtPastMonth: '4K+ orders this month',
  },
  {
    id: 'prod-003',
    name: 'Premium Sharbati Whole Wheat (Gehun)',
    hindiName: 'शरबती गेहूँ (प्रीमियम)',
    marathiName: 'शरबती गहू (प्रीमियम)',
    category: 'Grains',
    pricePerKg: 42,
    mrp: 58,
    discountPercent: 28,
    rating: 4.8,
    reviewCount: 2150,
    isBestSeller: false,
    isFreshCertified: true,
    availableQuantity: 12000,
    minOrderQuantity: 5,
    unit: 'kg',
    grade: 'Grade A+',
    farmLocation: 'Sehore Plains',
    district: 'Sehore',
    state: 'Madhya Pradesh',
    farmerName: 'Khot Grains Cooperative',
    farmerPhone: '+91 98901 23411',
    kisanId: 'MP-KISAN-770921',
    barcode: 'CRPNX-AGRI-MP03-51092',
    harvestDate: 'Machine sorted & stone-cleaned',
    organic: true,
    labCertificateNo: 'NPOP/ICAR/MP-2026-9022',
    labName: 'Central Institute of Agricultural Engineering Lab, Bhopal',
    labTestDate: '15 Sep 2026',
    labResidueResult: 'Zero Synthetic Residue - Certified Organic Wheat',
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80',
    description: 'Golden, heavy Sharbati wheat grains from nutrient-rich soil. Yields extremely soft, fragrant and fluffy rotis.',
    shelfLifeDays: 180,
    boughtPastMonth: '1K+ orders this month',
  },
  {
    id: 'prod-004',
    name: 'Salem Pure Turmeric Rhizomes (Haldi)',
    hindiName: 'सलेम शुद्ध हल्दी',
    marathiName: 'कोल्हापूर सेलम हळद',
    category: 'Spices',
    pricePerKg: 145,
    mrp: 210,
    discountPercent: 31,
    rating: 4.9,
    reviewCount: 980,
    isBestSeller: true,
    isFreshCertified: true,
    availableQuantity: 1800,
    minOrderQuantity: 1,
    unit: 'kg',
    grade: 'Grade A+',
    farmLocation: 'Sangli-Kolhapur Valley',
    district: 'Kolhapur',
    state: 'Maharashtra',
    farmerName: 'Yadav Heritage Farms',
    farmerPhone: '+91 98234 55678',
    kisanId: 'MH-KISAN-654120',
    barcode: 'CRPNX-AGRI-MH04-12940',
    harvestDate: 'Sun-dried unpolished fingers',
    organic: true,
    labCertificateNo: 'NABL/SPICES-BD/2026-3011',
    labName: 'Spices Board Quality Evaluation Lab, Kochi & Mumbai',
    labTestDate: '20 Sep 2026',
    labResidueResult: 'Curcumin 5.24% • Zero Lead Chromate (Pure Haldi PASS)',
    image: '/images/products/turmeric_haldi.jpg',
    description: 'High curcumin (5.2%) single-origin Salem turmeric fingers. 100% pure, natural color and exceptional medicinal value.',
    shelfLifeDays: 365,
    boughtPastMonth: '800+ orders this month',
  },
  {
    id: 'prod-005',
    name: 'Ratnagiri Alphonso Mango (Hapus - GI Tagged)',
    hindiName: 'रत्नागिरी हापूस आम (GI प्रमाणित)',
    marathiName: 'रत्नागिरी हापूस आंबा',
    category: 'Fruits',
    pricePerKg: 280,
    mrp: 380,
    discountPercent: 26,
    rating: 4.9,
    reviewCount: 4120,
    isBestSeller: true,
    isFreshCertified: true,
    availableQuantity: 950,
    minOrderQuantity: 1,
    unit: 'kg',
    grade: 'Grade A+',
    farmLocation: 'Devgad Coastal Belt',
    district: 'Ratnagiri',
    state: 'Maharashtra',
    farmerName: 'Narvekar Mango Orchards',
    farmerPhone: '+91 94220 33412',
    kisanId: 'MH-KISAN-992105',
    barcode: 'CRPNX-AGRI-MH05-77319',
    harvestDate: 'Naturally hay-ripened, carbide free',
    organic: true,
    labCertificateNo: 'GI/APEDA/MANGO-MH-2026-081',
    labName: 'APEDA Phytosanitary & GI Certification Center',
    labTestDate: '25 Sep 2026',
    labResidueResult: 'GI-Certified Authentic Devgad Ratnagiri Alphonso',
    image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&w=600&q=80',
    description: 'Original GI-tagged coastal Ratnagiri Alphonso. Saffron pulp, rich aroma, and thin peel.',
    shelfLifeDays: 10,
    boughtPastMonth: '5K+ orders this month',
  },
  {
    id: 'prod-006',
    name: 'Varanasi Red Potatoes (Pahari Aloo)',
    hindiName: 'वाराणसी लाल आलू',
    marathiName: 'वाराणसी लाल बटाटा',
    category: 'Vegetables',
    pricePerKg: 24,
    mrp: 36,
    discountPercent: 33,
    rating: 4.5,
    reviewCount: 1820,
    isBestSeller: false,
    isFreshCertified: true,
    availableQuantity: 6500,
    minOrderQuantity: 3,
    unit: 'kg',
    grade: 'Grade A',
    farmLocation: 'Ganga Agro Plains',
    district: 'Varanasi',
    state: 'Uttar Pradesh',
    farmerName: 'Mishra Krishi Farm',
    farmerPhone: '+91 94520 11982',
    kisanId: 'UP-KISAN-441280',
    barcode: 'CRPNX-AGRI-UP06-64102',
    harvestDate: 'Soil-cured winter potato harvest',
    organic: false,
    image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=600&q=80',
    description: 'Authentic Uttar Pradesh red-skinned potatoes with high starch, perfect for roasting and daily curries.',
    shelfLifeDays: 30,
    boughtPastMonth: '1.5K+ orders this month',
  },
  {
    id: 'prod-007',
    name: 'Solapur Bhagwa Pomegranate (Anaar)',
    hindiName: 'सोलापुर भगवा अनार',
    marathiName: 'सोलापूर डाळिंब (भगवा)',
    category: 'Fruits',
    pricePerKg: 110,
    mrp: 160,
    discountPercent: 31,
    rating: 4.5,
    reviewCount: 1540,
    isBestSeller: false,
    isFreshCertified: true,
    availableQuantity: 3200,
    minOrderQuantity: 1,
    unit: 'kg',
    grade: 'Grade A',
    farmLocation: 'Pandharpur Belt',
    district: 'Solapur',
    state: 'Maharashtra',
    farmerName: 'Deshmukh Agro Estates',
    farmerPhone: '+91 98600 77123',
    kisanId: 'MH-KISAN-331094',
    barcode: 'CRPNX-AGRI-MH07-88231',
    harvestDate: 'Fresh tree picked',
    organic: true,
    labCertificateNo: 'NABL/HORT-MH-2026-1144',
    labName: 'National Research Centre on Pomegranate (ICAR), Solapur',
    labTestDate: '22 Sep 2026',
    labResidueResult: 'Zero Chemical Fertilizers Detected (100% Natural)',
    image: 'https://images.unsplash.com/photo-1541344999736-83eca272f6fc?auto=format&fit=crop&w=600&q=80',
    description: 'Ruby red Bhagwa variety pomegranates with soft edible seeds and high natural sugar sweetness.',
    shelfLifeDays: 20,
    boughtPastMonth: '1.2K+ orders this month',
  },
  {
    id: 'prod-008',
    name: 'Organic Desi Chana (Whole Bengal Gram)',
    hindiName: 'देसी चना (साबुत)',
    marathiName: 'देशी हरभरा (अख्खा)',
    category: 'Pulses',
    pricePerKg: 78,
    mrp: 105,
    discountPercent: 25,
    rating: 4.6,
    reviewCount: 890,
    isBestSeller: false,
    isFreshCertified: true,
    availableQuantity: 4500,
    minOrderQuantity: 1,
    unit: 'kg',
    grade: 'Grade A',
    farmLocation: 'Latur Agro Market',
    district: 'Latur',
    state: 'Maharashtra',
    farmerName: 'Kulkarni Organic Pulses',
    farmerPhone: '+91 97632 10445',
    kisanId: 'MH-KISAN-512990',
    barcode: 'CRPNX-AGRI-MH08-30192',
    harvestDate: 'Current season crop',
    organic: false,
    image: '/images/products/desi_chana.jpg',
    description: 'Rich in dietary fiber and plant protein. Uniform brown seeds with zero artificial polish or moisture.',
    shelfLifeDays: 180,
    boughtPastMonth: '600+ orders this month',
  },
  {
    id: 'prod-009',
    name: 'Crisp Green Capsicum (Shimla Mirch)',
    hindiName: 'ताज़ी हरी शिमला मिर्च',
    marathiName: 'हिरवी ढोबळी मिरची',
    category: 'Vegetables',
    pricePerKg: 45,
    mrp: 65,
    discountPercent: 30,
    rating: 4.4,
    reviewCount: 760,
    isBestSeller: false,
    isFreshCertified: true,
    availableQuantity: 1600,
    minOrderQuantity: 1,
    unit: 'kg',
    grade: 'Grade A',
    farmLocation: 'Narayangaon Polyhouse',
    district: 'Pune',
    state: 'Maharashtra',
    farmerName: 'Ghorpade Hi-Tech Farms',
    farmerPhone: '+91 99214 90812',
    kisanId: 'MH-KISAN-224190',
    barcode: 'CRPNX-AGRI-MH09-41094',
    harvestDate: 'Polyhouse harvested',
    organic: true,
    labCertificateNo: 'NABL/MAH-AGRI/2026-5501',
    labName: 'Krishi Vigyan Kendra Soil & Produce Testing Lab, Narayangaon',
    labTestDate: '27 Sep 2026',
    labResidueResult: 'Grade A+ Polyhouse Organic Produce - PASS',
    image: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&w=600&q=80',
    description: 'Crisp, thick-walled bell peppers cultivated in protected greenhouse environment without harsh chemicals.',
    shelfLifeDays: 7,
    boughtPastMonth: '900+ orders this month',
  },
  {
    id: 'prod-010',
    name: 'Ludhiana Basmati Rice (1121 Extra Long)',
    hindiName: 'बासमती चावल (1121 लंबा दाना)',
    marathiName: 'बासमती तांदूळ (1121)',
    category: 'Grains',
    pricePerKg: 95,
    mrp: 130,
    discountPercent: 27,
    rating: 4.8,
    reviewCount: 3100,
    isBestSeller: true,
    isFreshCertified: true,
    availableQuantity: 7000,
    minOrderQuantity: 2,
    unit: 'kg',
    grade: 'Grade A+',
    farmLocation: 'Khanna Grain Market',
    district: 'Ludhiana',
    state: 'Punjab',
    farmerName: 'Gill Brothers Agro Mills',
    farmerPhone: '+91 98140 22910',
    kisanId: 'PB-KISAN-110482',
    barcode: 'CRPNX-AGRI-PB10-90812',
    harvestDate: 'Aged 12 months for fluffiness',
    organic: false,
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80',
    description: 'Authentic Punjab 1121 aged basmati rice. Extra-long slender grains that elongate up to 2.5x upon cooking with royal aroma.',
    shelfLifeDays: 365,
    boughtPastMonth: '3.5K+ orders this month',
  },
  {
    id: 'prod-011',
    name: 'Nagpur Sweet Oranges (Santra)',
    hindiName: 'नागपुर रसीला संतरा',
    marathiName: 'नागपूर संत्री',
    category: 'Fruits',
    pricePerKg: 65,
    mrp: 90,
    discountPercent: 28,
    rating: 4.7,
    reviewCount: 2210,
    isBestSeller: true,
    isFreshCertified: true,
    availableQuantity: 4200,
    minOrderQuantity: 1,
    unit: 'kg',
    grade: 'Grade A+',
    farmLocation: 'Katol Citrus Belt',
    district: 'Nagpur',
    state: 'Maharashtra',
    farmerName: 'Bhonsle Citrus Orchards',
    farmerPhone: '+91 97120 44109',
    kisanId: 'MH-KISAN-889102',
    barcode: 'CRPNX-AGRI-MH11-55412',
    harvestDate: 'Tree-ripened fresh pick',
    organic: true,
    labCertificateNo: 'NPOP/NAB/CITRUS-2026-9912',
    labName: 'ICAR-Central Citrus Research Institute, Nagpur',
    labTestDate: '26 Sep 2026',
    labResidueResult: '0.00% Pesticides Detected (Certified Organic PASS)',
    image: 'https://images.unsplash.com/photo-1582979512210-99b6a53386f9?auto=format&fit=crop&w=600&q=80',
    description: 'Juicy, sweet and tangy world-famous Nagpur oranges directly harvested from certified Katol orchards.',
    shelfLifeDays: 14,
    boughtPastMonth: '2.5K+ orders this month',
  },
  {
    id: 'prod-012',
    name: 'Kashmir Royal Delicious Red Apples (Seb)',
    hindiName: 'कश्मीरी रॉयल सेब',
    marathiName: 'काश्मिरी सफरचंद',
    category: 'Fruits',
    pricePerKg: 160,
    mrp: 220,
    discountPercent: 27,
    rating: 4.9,
    reviewCount: 3890,
    isBestSeller: true,
    isFreshCertified: true,
    availableQuantity: 2800,
    minOrderQuantity: 1,
    unit: 'kg',
    grade: 'Grade A+',
    farmLocation: 'Shopian Apple Valley',
    district: 'Shopian',
    state: 'Jammu and Kashmir',
    farmerName: 'Dar Himalayan Orchards',
    farmerPhone: '+91 94190 88214',
    kisanId: 'JK-KISAN-441203',
    barcode: 'CRPNX-AGRI-JK12-99014',
    harvestDate: 'Cold-chain stored Himalayan batch',
    organic: true,
    labCertificateNo: 'NPOP/NAB/HORT-JK-2026-4401',
    labName: 'SKUAST Kashmir Agri Quality Testing Center',
    labTestDate: '24 Sep 2026',
    labResidueResult: '100% Wax-Free Naturally Grown Apple (PASS)',
    image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=600&q=80',
    description: 'Crisp, aromatic, wax-free Himalayan apples from Shopian valley. High natural sweetness with firm texture.',
    shelfLifeDays: 25,
    boughtPastMonth: '4.8K+ orders this month',
  },
  {
    id: 'prod-013',
    name: 'Nashik Thompson Seedless Green Grapes (Angoor)',
    hindiName: 'ताज़ा नासिक अंगूर (थॉम्पसन)',
    marathiName: 'नाशिक द्राक्षे (थॉम्पसन सीडलेस)',
    category: 'Fruits',
    pricePerKg: 85,
    mrp: 120,
    discountPercent: 29,
    rating: 4.8,
    reviewCount: 2940,
    isBestSeller: false,
    isFreshCertified: true,
    availableQuantity: 3100,
    minOrderQuantity: 1,
    unit: 'kg',
    grade: 'Grade A+',
    farmLocation: 'Dindori Valley Vineyards',
    district: 'Nashik',
    state: 'Maharashtra',
    farmerName: 'Gadakh Premium Vineyards',
    farmerPhone: '+91 98223 77109',
    kisanId: 'MH-KISAN-772019',
    barcode: 'CRPNX-AGRI-MH13-66129',
    harvestDate: 'Morning hand-plucked bunch',
    organic: true,
    labCertificateNo: 'NPOP/NRCG-MH-2026-3392',
    labName: 'National Research Centre for Grapes (ICAR), Pune',
    labTestDate: '27 Sep 2026',
    labResidueResult: 'Export Residue Pass (EU Standard Compliant)',
    image: '/images/products/green_grapes.jpg',
    description: 'Crispy sweet Thompson seedless grapes with pristine natural bloom. Sourced from export-oriented vineyards of Dindori.',
    shelfLifeDays: 10,
    boughtPastMonth: '3K+ orders this month',
  },
  {
    id: 'prod-014',
    name: 'Fresh Desi Palak Leaves (Spinach)',
    hindiName: 'ताज़ा हरा पालक',
    marathiName: 'ताजी गावरान पालक भाजी',
    category: 'Vegetables',
    pricePerKg: 30,
    mrp: 45,
    discountPercent: 33,
    rating: 4.6,
    reviewCount: 1420,
    isBestSeller: false,
    isFreshCertified: true,
    availableQuantity: 1500,
    minOrderQuantity: 1,
    unit: 'kg',
    grade: 'Grade A+',
    farmLocation: 'Otur Green Belt',
    district: 'Pune',
    state: 'Maharashtra',
    farmerName: 'Jadhav Organic Greens',
    farmerPhone: '+91 98902 33108',
    kisanId: 'MH-KISAN-551029',
    barcode: 'CRPNX-AGRI-MH14-33108',
    harvestDate: 'Harvested early 5:00 AM today',
    organic: true,
    labCertificateNo: 'NPOP/NABL/PUNE-2026-8819',
    labName: 'MPKV Agri University Testing Lab, Pune',
    labTestDate: '28 Sep 2026',
    labResidueResult: 'Zero Nitrate / Chemical Residue (100% Organic PASS)',
    image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=600&q=80',
    description: 'Tender, farm-cut organic desi spinach leaves rich in iron and dietary chlorophyll. Cleansed and bundled fresh.',
    shelfLifeDays: 4,
    boughtPastMonth: '1.8K+ orders this month',
  },
  {
    id: 'prod-015',
    name: 'Nashik Fresh Cauliflower (Phool Gobhi)',
    hindiName: 'ताज़ी फूलगोभी',
    marathiName: 'ताजी फ्लॉवर (फुलकोबी)',
    category: 'Vegetables',
    pricePerKg: 32,
    mrp: 50,
    discountPercent: 36,
    rating: 4.5,
    reviewCount: 1680,
    isBestSeller: false,
    isFreshCertified: true,
    availableQuantity: 2800,
    minOrderQuantity: 1,
    unit: 'kg',
    grade: 'Grade A',
    farmLocation: 'Niphad Veggie Belt',
    district: 'Nashik',
    state: 'Maharashtra',
    farmerName: 'Shirsat Agri Farms',
    farmerPhone: '+91 94218 66291',
    kisanId: 'MH-KISAN-662910',
    barcode: 'CRPNX-AGRI-MH15-88120',
    harvestDate: 'Dense white curds with green leaves',
    organic: false,
    image: 'https://images.unsplash.com/photo-1568584711075-3d021a7c3ca3?auto=format&fit=crop&w=600&q=80',
    description: 'Solid, bright white cauliflower heads with tight curds and crisp texture. Ideal for curries, parathas and stir-fries.',
    shelfLifeDays: 8,
    boughtPastMonth: '2K+ orders this month',
  },
  {
    id: 'prod-016',
    name: 'Ooty Crunchy Hill Carrots (Gajar)',
    hindiName: 'ऊटी ताज़ी लाल गाजर',
    marathiName: 'ऊटी लाल गाजर',
    category: 'Vegetables',
    pricePerKg: 55,
    mrp: 80,
    discountPercent: 31,
    rating: 4.8,
    reviewCount: 2310,
    isBestSeller: true,
    isFreshCertified: true,
    availableQuantity: 3600,
    minOrderQuantity: 1,
    unit: 'kg',
    grade: 'Grade A+',
    farmLocation: 'Nilgiri Mountain Valleys',
    district: 'Nilgiris',
    state: 'Tamil Nadu',
    farmerName: 'Ramanathan Hill Farms',
    farmerPhone: '+91 94432 99201',
    kisanId: 'TN-KISAN-992014',
    barcode: 'CRPNX-AGRI-TN16-44019',
    harvestDate: 'Cold-mist mountain harvest',
    organic: true,
    labCertificateNo: 'NPOP/TN-AGRI/2026-6621',
    labName: 'TNAU Quality Testing Lab, Coimbatore',
    labTestDate: '26 Sep 2026',
    labResidueResult: '100% Organic Soil Certified (PASS)',
    image: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&w=600&q=80',
    description: 'Sweet, juicy and intensely vibrant red Nilgiri mountain carrots. High in beta-carotene with tender core.',
    shelfLifeDays: 14,
    boughtPastMonth: '2.9K+ orders this month',
  }
];

export const INITIAL_ORDERS = [
  {
    id: 'CNX-402-9981245-81204',
    orderNumber: 'CNX-402-9981245-81204',
    buyerName: 'Rahul Sharma',
    buyerEmail: 'rahul.sharma@gmail.com',
    buyerPhone: '+91 98210 55001',
    deliveryAddress: 'Flat 402, Sunshine Heights, Andheri West, Mumbai, Maharashtra 400053',
    district: 'Mumbai',
    state: 'Maharashtra',
    items: [
      {
        productId: 'prod-001',
        name: 'Fresh Hybrid Tomatoes (Tamatar)',
        pricePerKg: 28,
        quantity: 5,
        unit: 'kg',
        total: 140,
        image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=600&q=80',
      },
      {
        productId: 'prod-002',
        name: 'Nashik Red Onion (Pyaaz / Kanda)',
        pricePerKg: 34,
        quantity: 5,
        unit: 'kg',
        total: 170,
        image: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&w=600&q=80',
      }
    ],
    subtotal: 310,
    logisticsFee: 0,
    totalAmount: 310,
    paymentMethod: 'UPI / Direct Bank Transfer',
    status: 'Dispatched',
    trackingHistory: [
      {
        status: 'Order Placed',
        description: 'Payment confirmed via UPI',
        timestamp: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
        location: 'Buyer Portal',
      },
      {
        status: 'Harvest Packed',
        description: 'Quality inspected and crated at Nashik Farm Hub (Barcode Verified)',
        timestamp: new Date(Date.now() - 16 * 3600 * 1000).toISOString(),
        location: 'Nashik Farm Gate Sorting Hub',
      },
      {
        status: 'In Transit',
        description: 'En-route to Mumbai Delivery Hub via Temperature Controlled Carrier',
        timestamp: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
        location: 'Mumbai Regional Logistics Terminal',
      }
    ],
    createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
  }
];

export const INITIAL_FORECASTS = [
  {
    commodity: 'Tomato Hybrid',
    hindiName: 'टमाटर (Tomato Hybrid)',
    icon: '🍅',
    mandi: 'Nashik APMC Mandi (Pimpalgaon Hub)',
    currentPrice: 28,
    projectedPriceNextWeek: 35,
    projectedChange: '+25.0% Teji',
    projectedChangePercent: 25,
    trend: 'UP',
    action: 'HOLD',
    actionHeading: 'Bhav Badhega — Fasal Ko 4 Se 6 Din Rokein (HOLD)',
    actionExplanation:
      'Diwali retail demand aur aamad kam hone se rate ₹28 se badhkar ₹35/kg tak jayega. Abhi bechne ke bajaye 4-5 din hold karein, lagbhag 25% jyada munafa milega.',
    confidence: '94% Accurate',
    keyDrivers: [
      'Retail Demand Surge (+22%)',
      'Nashik Aamad 35% Kam Hui',
      'Cold Storage Linkage Active',
    ],
    projectedPrices: [
      { day: 'Day 1 (Aaj)', date: '04 Oct', price: 28 },
      { day: 'Day 2 (Kal)', date: '05 Oct', price: 29 },
      { day: 'Day 3', date: '06 Oct', price: 31 },
      { day: 'Day 4', date: '07 Oct', price: 33 },
      { day: 'Day 5', date: '08 Oct', price: 34 },
      { day: 'Day 6 (Best Day)', date: '09 Oct', price: 35 },
      { day: 'Day 7 (Peak)', date: '10 Oct', price: 35 },
    ],
  },
  {
    commodity: 'Nashik Red Onion',
    hindiName: 'प्याज (Nashik Red Onion)',
    icon: '🧅',
    mandi: 'Lasalgaon Mandi (Asia Largest Onion Yard)',
    currentPrice: 34,
    projectedPriceNextWeek: 42,
    projectedChange: '+23.5% Teji',
    projectedChangePercent: 23.5,
    trend: 'UP',
    action: 'HOLD',
    actionHeading: 'Bhav Me Bhari Teji — Maal Ko Warehouse Me Rokein (HOLD)',
    actionExplanation:
      'South Indian mandis (Bangalore & Chennai) se bhari demand aa rahi hai. Lasalgaon me stock kam ho raha hai. Rate agle hafte ₹42/kg touch karega.',
    confidence: '91% Accurate',
    keyDrivers: [
      'High Export Demand to UAE/Gulf',
      'Lasalgaon Buffer Stock Depleting',
      'Dry Weather Good for Storage',
    ],
    projectedPrices: [
      { day: 'Day 1 (Aaj)', date: '04 Oct', price: 34 },
      { day: 'Day 2 (Kal)', date: '05 Oct', price: 35 },
      { day: 'Day 3', date: '06 Oct', price: 37 },
      { day: 'Day 4', date: '07 Oct', price: 39 },
      { day: 'Day 5', date: '08 Oct', price: 41 },
      { day: 'Day 6 (Peak)', date: '09 Oct', price: 42 },
      { day: 'Day 7 (Peak)', date: '10 Oct', price: 42 },
    ],
  },
  {
    commodity: 'Varanasi Red Potatoes',
    hindiName: 'आलू (Red Pahari Aloo)',
    icon: '🥔',
    mandi: 'Varanasi Regional APMC Mandi',
    currentPrice: 24,
    projectedPriceNextWeek: 21,
    projectedChange: '-12.5% Manda',
    projectedChangePercent: -12.5,
    trend: 'DOWN',
    action: 'SELL',
    actionHeading: 'Bhav Gir Sakta Hai — Fasal Ko Turant Mandi Me Bechein (SELL NOW)',
    actionExplanation:
      'Agra aur Punjab se naye aloo ki aamad shuru ho rahi hai. Agle 5 dino me supply badhne se rate ₹24 se girkar ₹21/kg ho sakta hai. Stock na karein, turant sell karein.',
    confidence: '89% Accurate',
    keyDrivers: [
      'Punjab Nayi Aamad Shuru',
      'Cold Storages Releasing Old Batches',
      'Market Supply Oversaturated',
    ],
    projectedPrices: [
      { day: 'Day 1 (Aaj)', date: '04 Oct', price: 24 },
      { day: 'Day 2 (Kal)', date: '05 Oct', price: 23.5 },
      { day: 'Day 3', date: '06 Oct', price: 23 },
      { day: 'Day 4', date: '07 Oct', price: 22 },
      { day: 'Day 5', date: '08 Oct', price: 21.5 },
      { day: 'Day 6', date: '09 Oct', price: 21 },
      { day: 'Day 7', date: '10 Oct', price: 21 },
    ],
  },
  {
    commodity: 'Premium Sharbati Wheat',
    hindiName: 'गेहूं (MP Sharbati Gehun)',
    icon: '🌾',
    mandi: 'Sehore APMC Mandi (Madhya Pradesh)',
    currentPrice: 42,
    projectedPriceNextWeek: 46,
    projectedChange: '+9.5% Teji',
    projectedChangePercent: 9.5,
    trend: 'UP',
    action: 'HOLD',
    actionHeading: 'Stable Growth — Institutional Buyers Se Jyada Rate Milega (HOLD)',
    actionExplanation:
      'Top FMCG flour mills direct farm gate buying kar rahe hain. Standard mandi ke bajaye CropNex Institutional Tenders me quote karein jahan ₹46/kg tak rate milega.',
    confidence: '95% Accurate',
    keyDrivers: [
      'Flour Mill Bulk Buying Demand',
      'Low Government Buffer Stock',
      'Premium 14% Protein Content',
    ],
    projectedPrices: [
      { day: 'Day 1 (Aaj)', date: '04 Oct', price: 42 },
      { day: 'Day 2 (Kal)', date: '05 Oct', price: 43 },
      { day: 'Day 3', date: '06 Oct', price: 43.5 },
      { day: 'Day 4', date: '07 Oct', price: 44 },
      { day: 'Day 5', date: '08 Oct', price: 45 },
      { day: 'Day 6', date: '09 Oct', price: 46 },
      { day: 'Day 7', date: '10 Oct', price: 46 },
    ],
  },
  {
    commodity: 'Solapur Bhagwa Pomegranate',
    hindiName: 'अनार (Bhagwa Anaar)',
    icon: '🍎',
    mandi: 'Solapur Horticulture Market Yard',
    currentPrice: 110,
    projectedPriceNextWeek: 135,
    projectedChange: '+22.7% Teji',
    projectedChangePercent: 22.7,
    trend: 'UP',
    action: 'HOLD',
    actionHeading: 'Bhari Teji — Shaadi & Festival Season Ke Liye Rokein (HOLD)',
    actionExplanation:
      'Upcoming festive season aur wedding demand ke chalte Mumbai aur Delhi dry fruit & fresh fruit mandis me high grade Bhagwa anaar ki kami hai. Tree-fresh harvest 4-5 din baad bechein.',
    confidence: '93% Accurate',
    keyDrivers: [
      'Wedding Season Premium Demand',
      'APEDA Export Quota Active',
      'High Brix Sugar Content Certified',
    ],
    projectedPrices: [
      { day: 'Day 1 (Aaj)', date: '04 Oct', price: 110 },
      { day: 'Day 2 (Kal)', date: '05 Oct', price: 115 },
      { day: 'Day 3', date: '06 Oct', price: 122 },
      { day: 'Day 4', date: '07 Oct', price: 128 },
      { day: 'Day 5', date: '08 Oct', price: 132 },
      { day: 'Day 6', date: '09 Oct', price: 135 },
      { day: 'Day 7', date: '10 Oct', price: 135 },
    ],
  },
  {
    commodity: 'Garlic (Lahsun)',
    hindiName: 'लहसुन (Desi Lahsun)',
    icon: '🧄',
    mandi: 'Mandsaur / Indore APMC Mandi',
    currentPrice: 180,
    projectedPriceNextWeek: 215,
    projectedChange: '+19.4% Teji',
    projectedChangePercent: 19.4,
    trend: 'UP',
    action: 'HOLD',
    actionHeading: 'Bhav Badhega — Fasal Ko 5 Se 7 Din Rokein (HOLD)',
    actionExplanation:
      'Desi Lahsun ki mandis me supply kam hai aur masala processing units se heavy bulk enquiries aa rahi hain. Agle hafte rate ₹210-220/kg tak pahunch sakta hai.',
    confidence: '95% Accurate',
    keyDrivers: [
      'Spice Processing Factory Procurement',
      'Old Crop Stock Depleted Across MP/Rajasthan',
      'Cold Storage Holding Rates Firm',
    ],
    projectedPrices: [
      { day: 'Day 1 (Aaj)', date: '04 Oct', price: 180 },
      { day: 'Day 2 (Kal)', date: '05 Oct', price: 185 },
      { day: 'Day 3', date: '06 Oct', price: 192 },
      { day: 'Day 4', date: '07 Oct', price: 200 },
      { day: 'Day 5', date: '08 Oct', price: 208 },
      { day: 'Day 6 (Peak)', date: '09 Oct', price: 215 },
      { day: 'Day 7', date: '10 Oct', price: 215 },
    ],
  },
  {
    commodity: 'Ginger (Adrak)',
    hindiName: 'अदरक (Fresh Farm Adrak)',
    icon: '🫚',
    mandi: 'Wayanad / Pune APMC Mandi',
    currentPrice: 65,
    projectedPriceNextWeek: 78,
    projectedChange: '+20.0% Teji',
    projectedChangePercent: 20,
    trend: 'UP',
    action: 'HOLD',
    actionHeading: 'Bhav Badhega — Winter Tea & Medicine Demand (HOLD)',
    actionExplanation:
      'Sardi ki shuruat ke sath tea market aur Ayurvedic companies se taaza adrak ki maang badh rahi hai. Agle hafte ₹75-80/kg rate milne ki sambhavna hai.',
    confidence: '92% Accurate',
    keyDrivers: [
      'Winter Seasonal Demand Surge',
      'Inter-State Transport Corridors Clear',
      'Direct Beverage Brand Bulk Bidding',
    ],
    projectedPrices: [
      { day: 'Day 1 (Aaj)', date: '04 Oct', price: 65 },
      { day: 'Day 2 (Kal)', date: '05 Oct', price: 67 },
      { day: 'Day 3', date: '06 Oct', price: 70 },
      { day: 'Day 4', date: '07 Oct', price: 73 },
      { day: 'Day 5', date: '08 Oct', price: 76 },
      { day: 'Day 6 (Peak)', date: '09 Oct', price: 78 },
      { day: 'Day 7', date: '10 Oct', price: 78 },
    ],
  },
  {
    commodity: 'Red Chilli (Mirchi)',
    hindiName: 'लाल मिर्च (Guntur Teja Mirchi)',
    icon: '🌶️',
    mandi: 'Guntur APMC Yard (Andhra Pradesh)',
    currentPrice: 195,
    projectedPriceNextWeek: 230,
    projectedChange: '+17.9% Teji',
    projectedChangePercent: 17.9,
    trend: 'UP',
    action: 'HOLD',
    actionHeading: 'Bhav Teji Me Hai — Export & Spices Demand (HOLD)',
    actionExplanation:
      'Southeast Asia export contracts open hone se Guntur Yard me Teja mirchi ki aamad teji se khareedi ja rahi hai. Abhi hold karein.',
    confidence: '93% Accurate',
    keyDrivers: [
      'Export Quota Clearance to China & Vietnam',
      'High Capsaicin Content Premium',
      'Commercial Masala Mills Active',
    ],
    projectedPrices: [
      { day: 'Day 1 (Aaj)', date: '04 Oct', price: 195 },
      { day: 'Day 2 (Kal)', date: '05 Oct', price: 200 },
      { day: 'Day 3', date: '06 Oct', price: 210 },
      { day: 'Day 4', date: '07 Oct', price: 218 },
      { day: 'Day 5', date: '08 Oct', price: 225 },
      { day: 'Day 6 (Peak)', date: '09 Oct', price: 230 },
      { day: 'Day 7', date: '10 Oct', price: 230 },
    ],
  },
  {
    commodity: 'Soyabean',
    hindiName: 'सोयाबीन (Yellow Soyabean)',
    icon: '🌱',
    mandi: 'Indore / Latur Agro Market',
    currentPrice: 48,
    projectedPriceNextWeek: 53,
    projectedChange: '+10.4% Teji',
    projectedChangePercent: 10.4,
    trend: 'UP',
    action: 'HOLD',
    actionHeading: 'Bhav Sudhrega — Solvent Plants Bulk Buying (HOLD)',
    actionExplanation:
      'Solvent extraction plants aur edible oil mills crushing shuru kar rahe hain. Standard mandi ke bajaye institutional buyers ko bechein jahan ₹52-54/kg rate aayega.',
    confidence: '90% Accurate',
    keyDrivers: [
      'Crushing Plant Resumption',
      'Import Duty Hikes Supporting Domestic Crops',
      'Low Moisture Dry Batches in High Demand',
    ],
    projectedPrices: [
      { day: 'Day 1 (Aaj)', date: '04 Oct', price: 48 },
      { day: 'Day 2 (Kal)', date: '05 Oct', price: 49 },
      { day: 'Day 3', date: '06 Oct', price: 50 },
      { day: 'Day 4', date: '07 Oct', price: 51 },
      { day: 'Day 5', date: '08 Oct', price: 52 },
      { day: 'Day 6 (Peak)', date: '09 Oct', price: 53 },
      { day: 'Day 7', date: '10 Oct', price: 53 },
    ],
  },
  {
    commodity: 'Turmeric (Haldi)',
    hindiName: 'हल्दी (Salem Finger Haldi)',
    icon: '🌿',
    mandi: 'Salem / Nizamabad APMC Mandi',
    currentPrice: 145,
    projectedPriceNextWeek: 168,
    projectedChange: '+15.8% Teji',
    projectedChangePercent: 15.8,
    trend: 'UP',
    action: 'HOLD',
    actionHeading: 'Bhav Me Bhari Teji — Curcumin Extraction Demand (HOLD)',
    actionExplanation:
      'Pharma aur cosmetic units high-curcumin Salem finger haldi ki heavy purchasing kar rahe hain. Agle 6 dino me rate ₹165-170/kg touch karne ka anumaan hai.',
    confidence: '94% Accurate',
    keyDrivers: [
      'Pharma Grade Curcumin Extraction',
      'Nizamabad & Salem Yard Buffer Scarcity',
      'Festive Religious Consumption',
    ],
    projectedPrices: [
      { day: 'Day 1 (Aaj)', date: '04 Oct', price: 145 },
      { day: 'Day 2 (Kal)', date: '05 Oct', price: 148 },
      { day: 'Day 3', date: '06 Oct', price: 154 },
      { day: 'Day 4', date: '07 Oct', price: 160 },
      { day: 'Day 5', date: '08 Oct', price: 165 },
      { day: 'Day 6 (Peak)', date: '09 Oct', price: 168 },
      { day: 'Day 7', date: '10 Oct', price: 168 },
    ],
  },
  {
    commodity: 'Cotton (Kapas)',
    hindiName: 'कपास (Long Staple Kapas)',
    icon: '🧶',
    mandi: 'Rajkot / Yavatmal APMC Yard',
    currentPrice: 72,
    projectedPriceNextWeek: 68,
    projectedChange: '-5.5% Manda',
    projectedChangePercent: -5.5,
    trend: 'DOWN',
    action: 'SELL',
    actionHeading: 'Bhav Gir Sakta Hai — Turant Sell Karein (SELL NOW)',
    actionExplanation:
      'Gujarat aur Vidarbha me nayi kapas ki aamad achanak badh gayi hai. Ginning mills stock full kar chuki hain, isliye rate ₹72 se girkar ₹68/kg tak ja sakta hai.',
    confidence: '88% Accurate',
    keyDrivers: [
      'Gujarat Fresh Harvest Arrivals',
      'Spinning Mills Sufficient Inventories',
      'Global Cotton Futures Mild Dip',
    ],
    projectedPrices: [
      { day: 'Day 1 (Aaj)', date: '04 Oct', price: 72 },
      { day: 'Day 2 (Kal)', date: '05 Oct', price: 71 },
      { day: 'Day 3', date: '06 Oct', price: 70 },
      { day: 'Day 4', date: '07 Oct', price: 69 },
      { day: 'Day 5', date: '08 Oct', price: 69 },
      { day: 'Day 6', date: '09 Oct', price: 68 },
      { day: 'Day 7', date: '10 Oct', price: 68 },
    ],
  },
];

export const INITIAL_TENDERS = [
  {
    tenderId: 'TNDR-REL-2026-081',
    title: 'Reliance Retail / JioMart Fresh Direct Procurement',
    buyerName: 'Reliance Retail Ltd. (Fresh Mandi Division)',
    buyerType: 'Retail Giant',
    crop: 'Fresh Hybrid Tomatoes (Grade A+)',
    quantity: '15,000 kg (15 Tonnes)',
    benchmarkRate: '₹32 - ₹36 / kg',
    unitRate: 34,
    deliveryLocation: 'Reliance Distribution Center, Ghansoli (Navi Mumbai)',
    deadline: '08 Oct 2026 (In 3 Days)',
    status: 'Open for Bidding',
    paymentTerms: '24 Hours Direct Bank Escrow Payout',
    description:
      'Daily intake for Mumbai-Pune hypermarket network. Produce must be firm, red, sorted, and crate-packed at farm gate.',
  },
  {
    tenderId: 'TNDR-BB-2026-442',
    title: 'BigBasket Mega Fresh Intake — Lasalgaon Red Onions',
    buyerName: 'BigBasket (Innovative Retail Concepts Pvt Ltd)',
    buyerType: 'E-Grocery',
    crop: 'Nashik Red Onion (Garwa Grade A)',
    quantity: '30,000 kg (30 Tonnes)',
    benchmarkRate: '₹38 - ₹42 / kg',
    unitRate: 40,
    deliveryLocation: 'BigBasket Regional Fulfillment Hub, Chakan (Pune)',
    deadline: '09 Oct 2026 (In 4 Days)',
    status: 'Open for Bidding',
    paymentTerms: 'Automated NEFT within 24 Hours of Weighbridge Receipt',
    description:
      'Bulk seasonal procurement for retail consumer mesh-bags. Double-skin dry onions with minimum 45mm diameter required.',
  },
  {
    tenderId: 'TNDR-SAFAL-2026-119',
    title: 'Mother Dairy (Safal) — Premium Orchard Fresh Fruits',
    buyerName: 'Mother Dairy Fruit & Vegetable Pvt. Ltd. (Safal)',
    buyerType: 'Dairy & Fresh',
    crop: 'Solapur Bhagwa Pomegranate (Export Grade)',
    quantity: '10,000 kg (10 Tonnes)',
    benchmarkRate: '₹115 - ₹125 / kg',
    unitRate: 120,
    deliveryLocation: 'Safal Central Cold Terminal, Mangolpuri Belt',
    deadline: '10 Oct 2026 (In 5 Days)',
    status: 'Open for Bidding',
    paymentTerms: 'T+2 Days DBT with Official APMC Receipt',
    description:
      'Export quality Bhagwa pomegranates with soft seeds and ruby-red skin. Minimum fruit weight 180g each.',
  },
  {
    tenderId: 'TNDR-HALD-2026-902',
    title: 'Haldiram Foods International — Sharbati Wheat Contract',
    buyerName: 'Haldiram Foods International Ltd. (Procurement Unit)',
    buyerType: 'Food Processor',
    crop: 'Premium Sharbati Whole Wheat (Gehun)',
    quantity: '50 Tonnes (500 Quintals)',
    benchmarkRate: '₹4,400 - ₹4,650 / Quintal',
    unitRate: 45,
    deliveryLocation: 'Haldiram Manufacturing Plant, Nagpur Hub',
    deadline: '12 Oct 2026 (In 7 Days)',
    status: 'Open for Bidding',
    paymentTerms: '100% Escrow Advance upon QC Check',
    description:
      'Clean, machine-sorted MP Sharbati wheat required for premium bakery and bhujia manufacturing lines.',
  },
  {
    tenderId: 'TNDR-IRCTC-2026-305',
    title: 'Indian Railways (IRCTC) — Central Base Kitchen Bulk Potatoes',
    buyerName: 'IRCTC Directorate of Catering, Western Railway',
    buyerType: 'Govt Agency',
    crop: 'Varanasi Red Potatoes (Pahari Aloo)',
    quantity: '20,000 kg (20 Tonnes)',
    benchmarkRate: '₹24 - ₹28 / kg',
    unitRate: 26,
    deliveryLocation: 'IRCTC Base Kitchen Facility, CSMT Mumbai',
    deadline: '07 Oct 2026 (In 2 Days)',
    status: 'Closing Soon',
    paymentTerms: 'Treasury Linked Direct DBT within 48 Hours',
    description:
      'Firm red-skinned potatoes for daily train passenger meals. Must be clean, unsprouted, and dry.',
  },
  {
    tenderId: 'TNDR-NAFED-2026-771',
    title: 'NAFED National Buffer Stock — Certified Organic Pulses',
    buyerName: 'NAFED (National Agricultural Cooperative Marketing Federation)',
    buyerType: 'Govt Agency',
    crop: 'Organic Desi Chana (Whole Bengal Gram)',
    quantity: '40 Tonnes (400 Quintals)',
    benchmarkRate: '₹7,600 - ₹8,000 / Quintal',
    unitRate: 78,
    deliveryLocation: 'Central Warehouse Corporation (CWC), Latur',
    deadline: '11 Oct 2026 (In 6 Days)',
    status: 'Open for Bidding',
    paymentTerms: 'Direct Aadhaar DBT to Farmer Account under Price Support',
    description:
      'Government buffer stock procurement with dedicated +₹200/quintal bonus for NPOP organic certificate holders.',
  },
];

